### ISSUE TITLE
Does not work for large index 

### ISSUE THREAD

**Issue by benoitguigal** [federicotdn/inelastic#1]
I have a large index (~ 8 000 000 documents) and the script fails with error `TransportError(400, 'too_long_frame_exception', 'An HTTP line is larger than 4096 bytes.')`

**Comment by federicotdn** [comment]
Hello @benoitguigal, I've only tested the script with an index containing ~150000 documents, so there may be some bugs I've not stumbled upon yet. Do you have a more detailed exception backtrace? Also, when running with the `-v` option, at what completion percentage does the error occur?

**Comment by pratheekrebala** [comment]
FWIW - I believe this might be happening due to the `search_size` option where the URL for the GET request to `_mtermvectors` is too long. This is because the document ids for the request are being provided as GET parameters. Reducing the per-request size to something reasonable (in my case 150) did the trick for me.

For elasticsearch the maximum URL length is set at 4096 bytes.

If using smaller batches is not an option, you can change the  `http.max_initial_line_length` option to a higher value that works for you.

**Comment by federicotdn** [comment]
Fixed in https://github.com/federicotdn/inelastic/pull/5
